import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

export default [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // next-env.d.ts is generated by Next and rewritten on every build.
  // `.next-check` is the same build output under the name `make check-web`
  // gives it, kept apart from `.next` so the gate cannot corrupt a running
  // dev server. Both are generated, and neither is ours to lint.
  { ignores: [".next/**", ".next-check/**", "node_modules/**", "next-env.d.ts"] },
];
