"""Screening rules and filter models, free of I/O.

This module is the package's public API. Consumers import from the package root
only::

    from domain import build_company_metrics, evaluate_eligibility

Everything re-exported here is a supported contract. Anything not listed in
`__all__` is internal and may change without a version bump.

The package holds four things: the normalised models every other layer speaks in
(`models`, `scores`), the deterministic metric engine (`metrics`), the
eligibility screen with its universe rules (`eligibility`, `universe`), and
CompounderScore v1 (`scoring`, `curves`, `sectors`). None of them perform I/O, so
all of them are testable against hand-worked numbers.
"""

from domain.curves import Bands, Curve, CurveError, band, interpolate
from domain.eligibility import MARKET_CAP_DISCREPANCY_THRESHOLD, evaluate_eligibility
from domain.metrics import (
    DEFAULT_LIQUIDITY_WINDOW,
    average_dollar_volume,
    build_company_metrics,
    calculated_market_cap,
    distance_from_52w_high,
    enterprise_value,
    fcf_margin,
    fcf_margin_change,
    free_cash_flow,
    gross_margin,
    gross_margin_change,
    gross_profit_growth_yoy,
    growth_acceleration,
    high_52w,
    latest_close,
    latest_common_shares,
    low_52w,
    market_cap_discrepancy,
    net_cash,
    operating_margin,
    operating_margin_change,
    previous_yoy_revenue_growth,
    recent_revenue_growth,
    resolve_liquidity,
    resolve_market_cap,
    return_6m,
    return_12m,
    revenue_cagr_3y,
    share_count_growth_yoy,
    total_return,
    trading_days_used,
    ttm_free_cash_flow,
    ttm_revenue,
    ttm_revenue_growth,
    yoy_revenue_growth,
)
from domain.models import (
    USD,
    CompanyMetrics,
    CompanyProfile,
    EligibilityResult,
    EligibilityThresholds,
    EligibilityWarning,
    ExclusionReason,
    FinancialPeriod,
    MarketCapSource,
    PriceBar,
    VolumeBasis,
    normalise_ticker,
)
from domain.scores import (
    COMPOUNDER_V1,
    COMPOUNDER_V1_1,
    CURRENT_SCORE_VERSION,
    BenchmarkReturns,
    CompanyScore,
    ComponentScore,
    ComponentStatus,
    MetricUnit,
    RiskAssessment,
    RiskLevel,
    ScoreCategory,
    ScoreWarning,
    ScoringStatus,
    SubScore,
    ValuationBasis,
)
from domain.scoring import (
    GROWTH_MAX,
    LUMPY_GROWTH_BUDGET,
    LUMPY_PERSISTENCE_CEILING,
    MAX_REDISTRIBUTION_MULTIPLIER,
    MAX_TOTAL_PENALTY,
    MOMENTUM_MAX,
    QUALITY_MAX,
    RAW_SCORE_MAX,
    REBOUND_ACCELERATION_CAP,
    REBOUND_CAGR_CEILING,
    REBOUND_YOY_FLOOR,
    VALUATION_MAX,
    ScoringError,
    assess_risk,
    cash_runway_months,
    categorise,
    growth_adjusted_points,
    is_cyclical_rebound,
    relative_strength,
    risk_level,
    score_company,
    score_growth,
    score_momentum,
    score_quality,
    score_valuation,
    valuation_multiple,
)
from domain.sectors import is_unsupported_sector
from domain.universe import (
    SUPPORTED_EXCHANGES,
    is_common_stock,
    is_supported_exchange,
    is_supported_listing,
)

__all__ = [
    "COMPOUNDER_V1",
    "COMPOUNDER_V1_1",
    "CURRENT_SCORE_VERSION",
    "DEFAULT_LIQUIDITY_WINDOW",
    "GROWTH_MAX",
    "LUMPY_GROWTH_BUDGET",
    "LUMPY_PERSISTENCE_CEILING",
    "MARKET_CAP_DISCREPANCY_THRESHOLD",
    "MAX_REDISTRIBUTION_MULTIPLIER",
    "MAX_TOTAL_PENALTY",
    "MOMENTUM_MAX",
    "QUALITY_MAX",
    "RAW_SCORE_MAX",
    "REBOUND_ACCELERATION_CAP",
    "REBOUND_CAGR_CEILING",
    "REBOUND_YOY_FLOOR",
    "SUPPORTED_EXCHANGES",
    "USD",
    "VALUATION_MAX",
    "Bands",
    "BenchmarkReturns",
    "CompanyMetrics",
    "CompanyProfile",
    "CompanyScore",
    "ComponentScore",
    "ComponentStatus",
    "Curve",
    "CurveError",
    "EligibilityResult",
    "EligibilityThresholds",
    "EligibilityWarning",
    "ExclusionReason",
    "FinancialPeriod",
    "MarketCapSource",
    "MetricUnit",
    "PriceBar",
    "RiskAssessment",
    "RiskLevel",
    "ScoreCategory",
    "ScoreWarning",
    "ScoringError",
    "ScoringStatus",
    "SubScore",
    "ValuationBasis",
    "VolumeBasis",
    "assess_risk",
    "average_dollar_volume",
    "band",
    "build_company_metrics",
    "calculated_market_cap",
    "cash_runway_months",
    "categorise",
    "distance_from_52w_high",
    "enterprise_value",
    "evaluate_eligibility",
    "fcf_margin",
    "fcf_margin_change",
    "free_cash_flow",
    "gross_margin",
    "gross_margin_change",
    "gross_profit_growth_yoy",
    "growth_acceleration",
    "growth_adjusted_points",
    "high_52w",
    "interpolate",
    "is_common_stock",
    "is_cyclical_rebound",
    "is_supported_exchange",
    "is_supported_listing",
    "is_unsupported_sector",
    "latest_close",
    "latest_common_shares",
    "low_52w",
    "market_cap_discrepancy",
    "net_cash",
    "normalise_ticker",
    "operating_margin",
    "operating_margin_change",
    "previous_yoy_revenue_growth",
    "recent_revenue_growth",
    "relative_strength",
    "resolve_liquidity",
    "resolve_market_cap",
    "return_6m",
    "return_12m",
    "revenue_cagr_3y",
    "risk_level",
    "score_company",
    "score_growth",
    "score_momentum",
    "score_quality",
    "score_valuation",
    "share_count_growth_yoy",
    "total_return",
    "trading_days_used",
    "ttm_free_cash_flow",
    "ttm_revenue",
    "ttm_revenue_growth",
    "valuation_multiple",
    "yoy_revenue_growth",
]

__version__ = "0.1.0"
